
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Thu Jun 27 22:44:30 CEST 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 27;
  public static final int EQUALITY = 22;
  public static final int CONST = 8;
  public static final int COMMENT = 39;
  public static final int NOTEQUAL = 23;
  public static final int LPAREN = 32;
  public static final int SEMI = 29;
  public static final int CONTINUE = 10;
  public static final int FOR = 11;
  public static final int MINUS = 14;
  public static final int RPAREN = 33;
  public static final int AND = 21;
  public static final int RANGE = 12;
  public static final int LT = 26;
  public static final int COLUMN = 31;
  public static final int OR = 20;
  public static final int COMMA = 30;
  public static final int INC = 18;
  public static final int DIV = 16;
  public static final int PLUS = 13;
  public static final int LSQBRACE = 36;
  public static final int EOF = 0;
  public static final int RETURN = 4;
  public static final int EQUAL = 28;
  public static final int NEW = 6;
  public static final int error = 1;
  public static final int MUL = 15;
  public static final int NUMBER = 41;
  public static final int MOD = 17;
  public static final int IDENT = 44;
  public static final int BREAK = 9;
  public static final int VOID = 5;
  public static final int GTE = 25;
  public static final int LBRACE = 34;
  public static final int READ = 7;
  public static final int CHARCONST = 43;
  public static final int FINAL = 40;
  public static final int RBRACE = 35;
  public static final int BOOLCONST = 42;
  public static final int PROG = 2;
  public static final int DBLCOL = 38;
  public static final int RSQBRACE = 37;
  public static final int DEC = 19;
  public static final int GT = 24;
  public static final int PRINT = 3;
}

