
//----------------------------------------------------
// The following code was generated by CUP v0.10k
// Mon Feb 05 21:55:54 CET 2024
//----------------------------------------------------

package rs.ac.bg.etf.pp1;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LTE = 43;
  public static final int EQUALITY = 38;
  public static final int CONST = 32;
  public static final int NAMESPACE = 27;
  public static final int NOTEQUAL = 39;
  public static final int LPAREN = 6;
  public static final int SEMI = 5;
  public static final int CONTINUE = 31;
  public static final int FOR = 37;
  public static final int MINUS = 11;
  public static final int RPAREN = 7;
  public static final int AND = 36;
  public static final int LT = 42;
  public static final int OR = 35;
  public static final int COMMA = 12;
  public static final int INC = 21;
  public static final int DIV = 19;
  public static final int PLUS = 10;
  public static final int IF = 25;
  public static final int LSQBRACE = 16;
  public static final int EOF = 0;
  public static final int RETURN = 9;
  public static final int EQUAL = 8;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int MUL = 18;
  public static final int NUMBER = 23;
  public static final int MOD = 20;
  public static final int BREAK = 30;
  public static final int IDENT = 24;
  public static final int VOID = 14;
  public static final int GTE = 41;
  public static final int LBRACE = 3;
  public static final int ELSE = 26;
  public static final int READ = 29;
  public static final int CHARCONST = 33;
  public static final int RBRACE = 4;
  public static final int BOOLCONST = 34;
  public static final int PROG = 2;
  public static final int DBLCOL = 15;
  public static final int RSQBRACE = 17;
  public static final int DEC = 22;
  public static final int GT = 40;
  public static final int PRINT = 13;
}

